name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4' # The arm-none-eabi-gcc release to use.      
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: make all
      run: make
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
            build/dualdoser.elf
            build/dualdoser.dfu
            build/dualdoser.hex
            build/D11boot.hex
            build/D11boot.elf

