name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10.3-2021.10' # The arm-none-eabi-gcc release to use.
    - name: make app
      run: make
      working-directory: app
    - name: make bootloader
      run: make
      working-directory: bootloader/make


